run:
  tests: true
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - goerr113
    - maligned
    - gochecknoinits
    - funlen
    - exhaustivestruct
    - wrapcheck
    - testpackage
    - lll
    - errorlint
    - gosimple
    - gci
    - golint
    - exhaustruct
    - nonamedreturns
    - staticcheck
    - varnamelen
    - forbidigo
    - ifshort
    - ireturn
    - revive